# Generated by Django 4.0.4 on 2022-05-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_management', '0002_remove_user_about_remove_user_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
