# Generated by Django 4.0.4 on 2022-05-25 23:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user_profile', '0002_profile_biography_profile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_image',
            new_name='image',
        ),
    ]
