# Generated by Django 4.0.4 on 2022-05-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_profile', '0003_rename_profile_image_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
