# Generated by Django 4.0.4 on 2022-05-26 19:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user_profile', '0004_alter_profile_biography'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
